aplicaciones/panel/urls.py
from django.urls import path, include
from aplicaciones.panel import views as panel
app_name='panel'
urlpatterns = [
    path('', panel.InitPanel.as_view(), name='inicio'),
    path('tienda/producto/', panel.ProductoCrear.as_view(), name='producto_tienda'),
    path('tienda/producto/editar/<int:pk>/', panel.ProductoUpdate.as_view(), name='producto_tienda_update'),
    path('tienda/producto/delete/<int:pk>/', panel.ProductoDelete.as_view(), name='producto_tienda_delete'),
    path('tienda/media/', panel.MediaCreate.as_view(), name='media_files'),
    path('tienda/media/get_list', panel.GetListMedia.as_view(), name='get_media_files'),
    path('tienda/media/delete/', panel.MediaDelete.as_view(), name='get_media_delete'),

    path('tienda/categoria/crear/', panel.CategoriaCrear.as_view(), name='cat_crear'),
    path('tienda/categoria/create/', panel.CategiriaCreateView.as_view(), name='cat_create'),
    path('tienda/categoria/delete/<int:pk>/', panel.CategoriaDelete.as_view(), name='cat_delete'),
    path('tienda/categoria/update/', panel.CategoriaUpdate.as_view(), name='cat_update'),

    path('tienda/marca/crear/', panel.MarcaCrear.as_view(), name='marca_crar'),

    path('tienda/item/crear/', panel.ItemCrear.as_view(), name='item_crar'),

    path('tienda/producto/especificaciones/<int:pk>/', panel.EspecificacionCrear.as_view(), name='especificacion'),
    
] 

jmg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from ajax_select import urls as ajax_select_urls
from django.contrib.auth.views import LoginView, LogoutView

admin.autodiscover()
urlpatterns = [
    path('', include('aplicaciones.index.urls'), name='index'), 
    path('panel/', include('aplicaciones.panel.urls')), 
    path('admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    path('login/',LoginView.as_view(template_name='index/inicio.html'), name='inicio'),
    path('salir/', LogoutView.as_view(template_name='index/salir.html'), name="salir"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/panel/models.py
from django.db import models
import random
# Create your models here.
class MediaFiles(models.Model):
    media_img=models.ImageField(upload_to='MediaFiles/')
    short_name=models.CharField('Nombre', max_length=80)
    def __str__(self):
        return self.short_name

class Categoria(models.Model):
    cat=models.AutoField(primary_key=True)
    cat_nombre=models.CharField('Categoria', max_length=80, unique=True)
    def __str__(self):
        return self.cat_nombre

class Marcas(models.Model):
    marca=models.AutoField(primary_key=True)
    marca_nombre=models.CharField('Marca', max_length=80, unique=True) 
    def total_prod_marca(self):
        total=Producto.objects.filter(prod_marca=self.marca).count()
        return total
    def __str__(self):
        return self.marca_nombre 

class Producto(models.Model): 
    prod=models.AutoField(primary_key=True)
    prod_codigo=models.CharField('Codigo producto', max_length=35, unique=True)
    prod_nombre=models.CharField('Nombre', max_length=80)
    prod_descripcion=models.TextField('Descripción')
    prod_miniatura=models.ImageField('Miniatura', upload_to='MediaFiles/miniaturas')
    prod_fotos=models.ManyToManyField(MediaFiles, verbose_name='Imagenes relacionadas')
    prod_precio=models.FloatField('Precio')
    prod_descuento=models.IntegerField('Descuento sin %')
    prod_stock=models.FloatField('Cantidad de entrada a stock')
    prod_categoria=models.ForeignKey(Categoria, verbose_name='Tipo de categoria', on_delete=models.SET_NULL, blank=True, null=True)
    prod_marca=models.ForeignKey(Marcas, verbose_name='Marca', on_delete=models.CASCADE)
    prod_fecha_creacion=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.prod_codigo
    def prod_con_descuento(self): 
        precio=self.prod_precio
        descuento=self.prod_descuento
        resultado_descuento=descuento/100
        descuentoR=precio*resultado_descuento
        return round(precio-descuentoR, 2)


class ItemEspecificacion(models.Model):
    item=models.AutoField(primary_key=True)
    item_nombre=models.CharField('Item', max_length=80, unique=True)
    def __str__(self):
        return self.item_nombre

class EspecificacionProducto(models.Model):
    esp=models.AutoField(primary_key=True)
    esp_item=models.ForeignKey(ItemEspecificacion, verbose_name='Item', on_delete=models.CASCADE)
    esp_especificacion=models.CharField('Especificacion', max_length=50)
    esp_producto=models.ForeignKey(Producto, verbose_name='Producto', on_delete=models.CASCADE)
    def __str__(self):
        item=str(self.esp_item)
        esp=str(self.esp_especificacion)
        return item + ' ' +esp
    class Meta:
        unique_together = (("esp_item", "esp_producto"),)
        

    

aplicaciones/panel/forms.py
from django import forms
from aplicaciones.panel.models import Producto, MediaFiles, Categoria, EspecificacionProducto
from ajax_select.fields import AutoCompleteSelectMultipleField


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
    prod_fotos = AutoCompleteSelectMultipleField('mediaimg',required=False, help_text='Escriba nombre de la imagen a buscar')
    def __init__(self, *args, **kwargs):
        super(ProductoForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class MediaForm(forms.ModelForm):
    class Meta:
        model = MediaFiles
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(MediaForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

        self.fields['media_img'].widget.attrs.update({'@change': 'processFile($event)'})
        self.fields['short_name'].widget.attrs.update({'v-model': 'short_name'})

class CategoriaForm(forms.ModelForm): 
    class Meta:
        model = Categoria
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(CategoriaForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
class EspeficicacionForm(forms.ModelForm): 
    class Meta:
        model = EspecificacionProducto
        fields = ('esp_item','esp_especificacion')
    def __init__(self, *args, **kwargs):
        super(EspeficicacionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

aplicaciones/panel/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, View, UpdateView, DeleteView, View
from aplicaciones.panel.models import Producto, Categoria, MediaFiles, Marcas, EspecificacionProducto, ItemEspecificacion
from aplicaciones.panel.forms import ProductoForm, MediaForm, CategoriaForm, EspeficicacionForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from aplicaciones.index.eliminaciones import get_deleted_objects
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.contrib import messages
# Create your views here.
# Create your views here.
class InitPanel(TemplateView):
    template_name='panel/inicio.html'



class ProductoCrear(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'next'
    model = Producto
    template_name = "panel/crear.html"
    form_class = ProductoForm
    success_url = reverse_lazy('panel:producto_tienda')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_prod'] = Producto.objects.all()

        
        return context

class ProductoDelete(DeleteView):
    model = Producto
    template_name='eliminaciones.html'
    success_url = reverse_lazy('panel:producto_tienda')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        deletable_objects, model_count, protected = get_deleted_objects([self.object])
        #
        context['deletable_objects']=deletable_objects
        context['model_count']=dict(model_count).items()
        context['protected']=protected
        
        return context

class ProductoUpdate(UpdateView):
    model = Producto
    template_name = "panel/producto_editar.html"
    form_class = ProductoForm
    success_url = reverse_lazy('panel:producto_tienda')



class AjaxMediaResponse:
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super().form_valid(form)
        if self.request.is_ajax():
            media=MediaFiles.objects.values('id','media_img', 'short_name')
            media_list=list(media)
            data = {
                'pk': self.object.pk,
                'imgs': media_list,
            }
            return JsonResponse(data)
        else:
            return response

class MediaCreate(AjaxMediaResponse, CreateView):
    model = MediaFiles
    template_name = "panel/crear_medias.html"
    form_class = MediaForm
    success_url = reverse_lazy('panel:producto_tienda')

class GetListMedia(View):
    def get(self, request, *args, **kwargs):
        media=MediaFiles.objects.values('id','media_img', 'short_name')
        media_list=list(media)
        data = {
                'imgs': media_list,
            }
        return JsonResponse(data)
class MediaDelete(View):
    def get(self, request, *args, **kwargs):
        from django.core.files.storage import default_storage
        # OBTENEMOS EL ID A ELIMINAR DEL MEDIA
        id_name=request.GET.get('delete_id')
        # OBTENEMOS EL ARCHIVO DE IMAGEN DE LA BD
        img=MediaFiles.objects.get(id=id_name)
        # ELIMINAMOS EL OBJETO DE LA BD
        MediaFiles.objects.filter(id=id_name).delete()
        # ELIMINAMOS EL ARCHIVO DEL STORAGE
        default_storage.delete(img.media_img.path)
        # OBTENEMOS LA NUEVA LISTA ACTUALIZADA
        media=MediaFiles.objects.values('id','media_img', 'short_name')

        media_list=list(media)
        data = {
                'imgs': media_list,
            }

        return JsonResponse(data)

class CategoriaCrear(TemplateView):
    model=Categoria
    template_name='panel/crear_medias.html'
    form_class = CategoriaForm
    def post(self, request, *args, **kwargs):
        from django.core.exceptions import ValidationError
        import json
        # body_unicode = request.body.decode('utf-8')
        body = json.loads(request.body)
        try:
            categoriObj=Categoria(cat_nombre=body.get('cat_nombre').title())
            categoriObj.full_clean()
            categoriObj.save()
            catergoria=Categoria.objects.filter(cat=categoriObj.pk).values()
            cat_list=list(catergoria)
            data = {
                    'cat_list': cat_list,
                    'status': True,
                }
            return JsonResponse(data) 
        except ValidationError as e:
            # Do something based on the errors contained in e.message_dict.
            # Display them to a user, or handle them programmatically.
            
            data = {
                    'error': 'error',
                    'type': dict(e),
                    'status': False,
                    
                }
            return JsonResponse(data, status=400)
    
class CategiriaCreateView(CreateView):
    model = Categoria
    template_name='panel/create_generico.html'
    form_class=CategoriaForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_data'] = Categoria.objects.all()
        
        return context


class CategoriaDelete(DeleteView):
    model = Categoria
    template_name='eliminaciones.html'
    success_url = reverse_lazy('panel:cat_create')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        deletable_objects, model_count, protected = get_deleted_objects([self.object])
        #
        context['deletable_objects']=deletable_objects
        context['model_count']=dict(model_count).items()
        context['protected']=protected
        
        return context

class CategoriaUpdate(View):
    def post(self, request, *args, **kwargs):
        from django.db import IntegrityError
        import json
        # body_unicode = request.body.decode('utf-8')
        body = json.loads(request.body)
        try:
            ID=body.get('ID')
            text_update=body.get('valor')
            Categoria.objects.filter(cat=ID).update(cat_nombre=text_update)
            catergoria=Categoria.objects.filter(cat=ID).values()
            cat_list=list(catergoria)
            data = {
                    'cat_list': cat_list,
                    'status': True,
                }
            return JsonResponse(data) 
        except IntegrityError as e:
            # Do something based on the errors contained in e.message_dict.
            # Display them to a user, or handle them programmatically.            
            data = {
                    'error': 'error',
                    'type': 'Ya existe un elemento con ese nombre',
                    'status': False,
                }
            return JsonResponse(data, status=400)
        
    
class MarcaCrear(View):
    def post(self, request, *args, **kwargs):
        from django.core.exceptions import ValidationError
        import json
        # body_unicode = request.body.decode('utf-8')
        body = json.loads(request.body)
        try:
            marca_obj=Marcas(marca_nombre=body.get('marca').title())
            marca_obj.full_clean()
            marca_obj.save()
            qry_marcas=Marcas.objects.filter(marca=marca_obj.pk).values()
            marca_list=list(qry_marcas)
            data = {
                    'obj_list': marca_list,
                    'status': True,
                }
            return JsonResponse(data) 
        except ValidationError as e:
            # Do something based on the errors contained in e.message_dict.
            # Display them to a user, or handle them programmatically.
            
            data = {
                    'error': 'error',
                    'type': dict(e), 
                    'status': False,
                     
                }
            return JsonResponse(data, status=400)

class EspecificacionCrear(CreateView):
    model = EspecificacionProducto
    template_name = "panel/especificaciones.html"
    form_class = EspeficicacionForm
    success_url = reverse_lazy('panel:producto_tienda')
    def get_success_url(self, **kwargs):         
        return reverse_lazy('panel:especificacion', kwargs = {'pk': self.kwargs.get('pk')})
    def form_valid(self, form):
        form.instance.esp_producto=Producto.objects.get(prod=self.kwargs.get('pk'))
        try:
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('esp_item','Existe una especificacion del mismo tipo')
            messages.warning(self.request, 'Existe una especificacion del mismo tipo, agregue uno nuevo.')
            return self.form_invalid(form)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['EspecificacionProducto'] = EspecificacionProducto.objects.all()
        context['ItemEspecificacion'] = ItemEspecificacion.objects.all()
        
        return context



class ItemCrear(View):
    def post(self, request, *args, **kwargs):
        from django.core.exceptions import ValidationError
        import json
        # body_unicode = request.body.decode('utf-8')
        body = json.loads(request.body)
        try:
            obj=ItemEspecificacion(item_nombre=body.get('item').title())
            obj.full_clean()
            obj.save()
            qry=ItemEspecificacion.objects.filter(item=obj.pk).values()
            lista=list(qry)
            data = {
                    'obj_list': lista,
                    'status': True,

templates/panel/crear.html
{% extends "admin-jmg/base.html" %}

{% block contenido %}
<div id="app">

    {{fom_cat}}
    <div class="collapse" id="collapseExample">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Añadir </strong>
            </div>
            <div class="card-body">

                <form action="" method="post" id="Form-oducto" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    <div class="row">
                        {% for input in form %}

                        
                        {% if input.name == 'prod_categoria' or input.name == 'prod_marca'%}

                        {% if input.name == 'prod_categoria' %}

                        <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-addon">{{input.label}}</div>
                                        {{input}}
                                        <a href="#" onclick="crear_categoria('{{ csrf_token }}')"
                                            class="input-group-addon"><i class="fa fa-plus-circle"></i></a>
                                    </div>
                                </div>
                            </div>

                        {% endif %}

                        {% if input.name == 'prod_marca' %}

                        <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-addon">{{input.label}}</div>
                                        {{input}}
                                        <a href="#" onclick="crear_marca()"
                                            class="input-group-addon"><i class="fa fa-plus-circle"></i></a>
                                    </div>
                                </div>
                            </div>

                        {% endif %}

                        {% else %}
                        <div class="col-md-3 mb-3">
                            {{input.label}}
                            {{input}}
                            <small class="form-text text-muted">{{input.help_text}}</small>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <button type="submit" @click="NuevoProducto" class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </div>



    <div class="card">
        <div class="card-header">
            <strong class="card-title">
                <button class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button"
                    aria-expanded="false" aria-controls="collapseExample">Añadir</button>
            </strong>
        </div>
        <div class="card-body">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Descripcion</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Descuento</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Categoria</th>
                        <th scope="col">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in list_prod %}
                    <tr>
                        <th scope="row">{{item.prod}}</th>
                        <td>{{item.prod_nombre|truncatewords:3}}</td>
                        <td>{{item.prod_descripcion|truncatewords:5}}</td>
                        <td>{{item.prod_precio}}</td>
                        <td>{{item.prod_descuento}}%</td>
                        <td>{{item.prod_stock}}</td>
                        <td>{{item.prod_categoria}}</td>
                        <td>
                            <a class="btn btn-outline-danger" title="Eliminar"
                                href="{% url 'panel:producto_tienda_delete' item.prod %}" role="button"><i
                                    class="fa fa-trash-o"></i></a>
                            <a class="btn btn-outline-secondary" title="Editar"
                                href="{% url 'panel:producto_tienda_update' item.prod %}" role="button"><i
                                    class="fa fa-edit"></i></a>
                            <a class="btn btn-outline-success" title="Añadir especificaciones" href="{% url 'panel:especificacion' item.prod %}" role="button"><i class="fa  fa-plus-square-o"></i</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>





</div>
{% endblock contenido %}
{% block script %}
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="{% static 'panel/js/crear_prodcto.js' %}"></script> 

{% endblock script %}

templates/panel/crear_medias.html
{% extends "admin-jmg/base.html" %}

{% block contenido %}
{% load static %}
<div id="app">


    <div class="card">
        <div class="card-header">
            <strong class="card-title">
                <button type="button" class="btn btn-primary" data-toggle="modal"
                    data-target="#exampleModalCenter">Añadir</button>
            </strong>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4" v-for="item in imgs">
                    <div class="card mb-4 shadow-sm">
                        <img  v-bind:src="'/media/'+item.media_img" class="bd-placeholder-img card-img-top img-thumbnail" alt="">
                        <title>Placeholder</title>
                    </img>
                       
                        <div class="card-body">
                            <p class="card-text">[[item.short_name]]</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary" @click="delete_img(item.id)">Eliminar</button>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>




    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Añadir nueva imagen</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="" method="post" id="Form-media" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock contenido %}

{% block script %}
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="{% static 'panel/js/crear_media.js' %}"></script>

{% endblock script %}

templates/panel/create_generico.html
{% extends "admin-jmg/base.html" %}
{% block contenido %}
<div class="card">
    <div class="card-header">

        <button type="button" class="btn btn-outline-success" onclick="crear_categoria()" title="Añadir"><i
                class="fa fa-plus-circle"></i></button>
    </div>
    <div class="card-body">
        <table class="table" id="tabla_categoria">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Eliminar</th>
                    <th scope="col">Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for item in list_data %}
                <tr>
                    <th scope="row">{{item.cat}}</th>
                    <td>{{item.cat_nombre}}</td>
                    <td>
                        <a href="{% url 'panel:cat_delete' item.cat %}"><i class="fa fa-trash-o"></i></a>
                    </td>
                    <td>
                        <a href="#" onclick="Update_categoria({{item.cat}})"><i class="fa fa-edit"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>

    </div>
</div>
{% endblock contenido %}
{% block script %}
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="{% static 'panel/js/crea_categoria.js' %}"></script>
{% endblock script %}

templates/panel/especificaciones.html
{% extends "admin-jmg/base.html" %}
{% block contenido %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
            {{ message }}
          </div>
    {% endfor %}
</ul>
{% endif %}
<form action="" method="POST">
    <div class="row">
        {% csrf_token %}
        {% for input in form %}
        {% if input.name == 'esp_item' %}
        <div class="col-md-4 mb-4">
            <div class="form-group">
                <div class="input-group">
                    {{input.erros}}
                    <div class="input-group-addon">{{input.label}}</div>
                    {{input}}
                    <a href="#" onclick="crear_item()" class="input-group-addon"><i
                            class="fa fa-plus-circle"></i></a>
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-md-4 mb-4">
                <div class="form-group">
                    <div class="input-group">
                            {{input.erros}}
                        <div class="input-group-addon">{{input.label}}</div>
                        {{input}}
                    </div>
                </div>
        </div>
        {% endif %}


        {% endfor %}
        <div class="col-sm-4">
            <button class="btn btn-primary btn-sm" type="submit">Añadir</button>
        </div>
    </div>
</form>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Producto</th>
            <th scope="col">Item</th>
            <th scope="col">Especificacion</th>
        </tr>
    </thead>
    <tbody>
        {% for item in EspecificacionProducto %}    
        <tr>
            <th scope="row">{{item.esp_producto}}</th>
            <td>{{item.esp_item}}</td>
            <td>{{item.esp_especificacion}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}

{% block script %}
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="{% static 'panel/js/crear_especificacion.js' %}"></script> 

{% endblock script %}

templates/panel/inicio.html
{% extends "admin-jmg/base.html" %}

{% block contenido %}

  <div class="row justify-content-md-center"> 
  <div class="card"> 
    <div class="card-body">
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-outline-primary">Inicio</button>
            <button type="button" class="btn btn-outline-primary">Abrir un nuevo ticket</button>
            <button type="button" class="btn btn-outline-primary">comprobar el estado del ticket</button>
          </div>
    </div>
</div>
</div>

<div class="card">
    <div class="card-header">
        <strong>Bienvenido al Centro de Soporte </strong>
    </div>
    <div class="card-body">
        <p class="card-text">Para agilizar las solicitudes de soporte y brindarle un mejor servicio, utilizamos un sistema de tickets de soporte. A cada solicitud de soporte se le asigna un número de ticket único que puede usar para rastrear el progreso y las respuestas en línea. Para su referencia, proporcionamos archivos completos e historial de todas sus solicitudes de soporte. Se requiere una dirección de correo electrónico válida para enviar un ticket.</p>
    </div>
</div>

{% endblock contenido %} 

templates/panel/producto_editar.html
{% extends "admin-jmg/base.html" %}

{% block contenido %}
<div class="card">
    <div class="card-header">
        <strong class="card-title">Añadir </strong>
    </div>
    <div class="card-body">

        <form action="" method="post" id="Form-oducto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            <div class="row">
                {% for input in form %}
                <div class="col-md-3 mb-3">
                    {{input.label}}
                    {{input}}
                    <small class="form-text text-muted">{{input.help_text}}</small>
                </div>
                {% endfor %}
            </div>
            <button type="submit" @click="NuevoProducto" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>
{% endblock contenido %}