aplicaciones/index/urls.py
from django.urls import path, include
from aplicaciones.index import views as index

app_name='index'
urlpatterns = [
    path('', index.IndexPage.as_view(), name='inicio'),
    path('jmg-shoping/', index.JmgShop.as_view(), name='shop'), 
    path('jmg-shoping/buscar/', index.JmgShopBuscar.as_view(), name='busqueda'),
    path('jmg-shoping/detalles/<int:pk>/', index.TiendaDetalleProducto.as_view(), name='detalle'),
    path('jmg-shoping/add_compras/<slug:codigo>/<int:cantidad>/', index.add_compra.as_view(), name='add_compra'),
    path('jmg-shoping/check/list/', index.CheckListCompra.as_view(), name='check_compra'),
]

jmg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from ajax_select import urls as ajax_select_urls
from django.contrib.auth.views import LoginView, LogoutView

admin.autodiscover()
urlpatterns = [
    path('', include('aplicaciones.index.urls'), name='index'), 
    path('panel/', include('aplicaciones.panel.urls')), 
    path('admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    path('login/',LoginView.as_view(template_name='index/inicio.html'), name='inicio'),
    path('salir/', LogoutView.as_view(template_name='index/salir.html'), name="salir"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index/check_list.html
{% extends 'index/base_tienda.html' %}
{% block contenido %}
<br>
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Producto</th>
                            <th scope="col">Precio</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{tabla|safe}}
                        
                        <!-- <tr class="bottom_button">
                            <td>
                                <a class="gray_btn" href="#">Update Cart</a>
                            </td>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <div class="cupon_text d-flex align-items-center">
                                    <input type="text" placeholder="Coupon Code">
                                    <a class="primary-btn" href="#">Apply</a>
                                    <a class="gray_btn" href="#">Close Coupon</a>
                                </div>
                            </td>
                        </tr> -->
                        <tr>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <h5>Subtotal</h5>
                            </td>
                            <td>
                                <h5>${{total}}</h5>
                            </td>
                        </tr>
                        <!-- <tr class="shipping_area">
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <h5>Shipping</h5>
                            </td>
                            <td>
                                <div class="shipping_box">
                                    <ul class="list">
                                        <li><a href="#">Flat Rate: $5.00</a></li>
                                        <li><a href="#">Free Shipping</a></li>
                                        <li><a href="#">Flat Rate: $10.00</a></li>
                                        <li class="active"><a href="#">Local Delivery: $2.00</a></li>
                                    </ul>
                                    <h6>Calculate Shipping <i class="fa fa-caret-down" aria-hidden="true"></i></h6>
                                    <select class="shipping_select">
                                        <option value="1">Bangladesh</option>
                                        <option value="2">India</option>
                                        <option value="4">Pakistan</option>
                                    </select>
                                    <select class="shipping_select">
                                        <option value="1">Select a State</option>
                                        <option value="2">Select a State</option>
                                        <option value="4">Select a State</option>
                                    </select>
                                    <input type="text" placeholder="Postcode/Zipcode">
                                    <a class="gray_btn" href="#">Update Details</a>
                                </div>
                            </td>
                        </tr> -->
                        <tr class="out_button_area">
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>

                            </td>
                            <td>
                                <div class="checkout_btn_inner d-flex align-items-center">
                                    <a class="gray_btn" href="#">Continuar comprando</a>
                                    <a class="primary-btn" href="#">Proceder a pago</a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<form action="/procesar-pago" method="POST">
    <script
      src="https://www.mercadopago.com.mx/integrations/v1/web-tokenize-checkout.js"
      data-public-key="TEST-e9acc660-133a-4785-ab96-aafe7ee11abf"
      data-transaction-amount="100.00">
    </script>
  </form>
{% endblock contenido %}

templates/index/detalle_producto.html
{% extends 'index/base_tienda.html' %}
{% block contenido %}
{% load humanize %}

<!-- Start Banner Area -->
<!-- <section class="banner-area organic-breadcrumb">
            <div class="container">
                <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                    <div class="col-first">
                        <h1>Detalle Producto</h1>
                        <nav class="d-flex align-items-center">
                            <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                            <a href="#">Shop<span class="lnr lnr-arrow-right"></span></a>
                            <a href="single-product.html">product-details</a>
                        </nav>
                    </div>
                </div>
            </div>
        </section> -->
<!-- End Banner Area -->

<!--================Single Product Area =================-->
<div class="product_image_area">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-6">
                <div class="main-carousel">
                    {% for item in object.prod_fotos.all %}
                    <div class="carousel-cell"><img src="{{item.media_img.url}}" width="500px" alt=""></div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>{{object.prod_nombre}}</h3>
                    <h2>${{object.prod_con_descuento|intcomma}}</h2>
                    <del>Antes: ${{object.prod_precio|intcomma}}.</del>
                    <ul class="list">
                        <li><a class="active" href="#"><span>Categoria</span> : {{object.prod_categoria}}</a></li>
                        <li><a href="#"><span>Disponibles</span> : {{object.prod_stock|intword}}</a></li>
                    </ul>
                    <p>{{object.prod_descripcion|truncatewords:10}}....</p>
                    <div class="product_count">
                        <label for="qty">Cantidad:</label>
                        <input type="text" name="qty" id="sst" min="1" value="1" title="Quantity:"
                            class="input-text qty">
                        <button
                            onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                            class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>
                        <button
                            onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
                            class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>
                    </div>
                    <div class="card_area d-flex align-items-center">
                        <a class="primary-btn" href="#" onclick="añadir_element()">Añadir</a>
                        <!-- <a class="icon_btn" href="#"><i class="lnr lnr lnr-diamond"></i></a>
                        <a class="icon_btn" href="#"><i class="lnr lnr lnr-heart"></i></a> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--================End Single Product Area =================-->



<!--================Product Description Area =================-->
<section class="product_description_area">
    <div class="container">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
                    aria-selected="true">Descripcion</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                    aria-controls="profile" aria-selected="false">Especificaciones</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <p>{{object.prod_descripcion}}</p>
            </div>
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                            

                            {% for item in detalles_obj %}
                            <tr>
                                <td>
                                    <h5>{{item.esp_item}}</h5>
                                </td>
                                <td>
                                    <h5>{{item.esp_especificacion}}</h5>
                                </td>
                            </tr>
                            {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>


        </div>
    </div>
</section>
<!--================End Product Description Area =================-->


{% endblock contenido %}

{% block script %}
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<script>


    var elem = document.querySelector('.main-carousel');
    var flkty = new Flickity(elem, {
        // options
        cellAlign: 'left',
        contain: true,
        freeScroll: true,
        wrapAround: true
    });

function añadir_element() {
    var result = document.getElementById('sst').value
    window.location.href = `/jmg-shoping/add_compras/{{object.prod_codigo}}/${result}/?detalle={{view.kwargs.pk}}`;
}

</script>
{% endblock script %}

templates/index/inicio.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ela Admin - HTML5 Admin Template</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link type="image/x-icon" href="{% static 'imagenes/icons8-wolf-filled-24.png' %}" rel="icon" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'administracion/assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'administracion/assets/css/style.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
</head>
<body class="bg-secondary">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="{% static 'imagenes/path12.png' %}" alt="">
                    </a>
                </div>
                <div class="login-form">
                    <form method="post"> 
                            {% csrf_token %}
                        <div class="form-group">
                            <label>Usuario</label>
                            <input type="text" class="form-control" name="username" placeholder="Usuario">
                        </div>
                        <div class="form-group">
                            <label>Contraseña</label>
                            <input type="password" class="form-control" name="password" placeholder="Contraseña">
                        </div>
                        <div class="checkbox">
                            <label class="pull-right">
                                <a href="#">Olvido su contraseña?</a>
                            </label>

                        </div>
                        <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">Entrar</button>
                        <!-- <div class="social-login-content">
                            <div class="social-button">
                                <button type="button" class="btn social facebook btn-flat btn-addon mb-3"><i class="ti-facebook"></i>Sign in with facebook</button>
                                <button type="button" class="btn social twitter btn-flat btn-addon mt-2"><i class="ti-twitter"></i>Sign in with twitter</button>
                            </div>
                        </div> -->
                       
                    </form>
                </div>
            </div>
        </div> 
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="assets/js/main.js"></script>

</body>
</html>

templates/index/jmg_shop.html
{% extends 'index/base_tienda.html' %}
{% block contenido %}
{% load humanize %}
{% load get_total_marca_x_categoria %}
  	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
            <div class="container">
                <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                    <div class="col-first">
                        <h1>Categorias</h1>
                        <nav class="d-flex align-items-center">
                            <a href="index.html">Inicio<span class="lnr lnr-arrow-right"></span></a>
                            <a href="#">Tienda<span class="lnr lnr-arrow-right"></span></a>
                            <a href="category.html">Buscar</a>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Banner Area -->
		
        <div class="container">
		<div class="row">
			<div class="col-xl-3 col-lg-4 col-md-5">
				<div class="sidebar-categories">
					<div class="head">Buscar por categoria</div>
					
					<div class="list-group"> 
							{% for item in categira_list %}
							<a href="?cat={{item.cat}}" class="list-group-item list-group-item-action {% if categoria|striptags == item.cat|striptags %}active{% endif %}">{{item.cat_nombre}}</a>
							{% endfor %}
						  </div>
				</div> 
				<div class="sidebar-filter mt-50">
					<div class="top-filter-head">Marcas</div>
					<div class="common-filter">
						<div class="list-group">
							{% for item in marcas_list %}
							{% if view.request.GET.cat|get_marca_x_cat:item.marca != 0 %}
							<a href="?cat={{view.request.GET.cat}}&marca={{item.marca}}" class="list-group-item list-group-item-action {% if marca|striptags == item.marca|striptags %}active{% endif %}">{{item.marca_nombre}} ( {{view.request.GET.cat|get_marca_x_cat:item.marca}} )</a>
							{% endif %}
							{% endfor %}
						</div>
					</div>
				
					<!-- <div class="common-filter">
						<div class="head">Precio</div>
						<div class="price-range-area">
							<div id="price-range"></div>
							<div class="value-wrapper d-flex">
								<div class="price">Price:</div>
								<span>$</span>
								<div id="lower-value"></div>
								<div class="to">to</div>
								<span>$</span>
								<div id="upper-value"></div>
							</div>
						</div>
					</div> -->
				</div>
			</div>
			<div class="col-xl-9 col-lg-8 col-md-7">
				<!-- Start Filter Bar -->
				<div class="filter-bar d-flex flex-wrap align-items-center">
					<!-- <div class="sorting">
						<select>
							<option value="1">Default sorting</option>
							<option value="1">Default sorting</option>
							<option value="1">Default sorting</option>
						</select>
					</div>
					<div class="sorting mr-auto">
						<select>
							<option value="1">Show 12</option>
							<option value="1">Show 12</option>
							<option value="1">Show 12</option>
						</select>
					</div> -->
					
					{% if is_paginated %}
					<div class="pagination">
						{% if page_obj.has_previous %}
						<a href="?cat={{categoria}}{% if view.request.GET.marca != None %}&marca={{view.request.GET.marca}}{% endif %}&page={{ page_obj.previous_page_number }}" class="prev-arrow"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
						{% endif %}
						{% for page in page_obj.paginator.page_range %}
								<a href="?cat={{categoria}}{% if view.request.GET.marca != None %}&marca={{view.request.GET.marca}}{% endif %}&page={{ page }}" class="{% if page_obj.number == page %}active{% endif %}">{{ page }}</a>
						{% endfor %}
						{% if page_obj.has_next %}
						<a href="?cat={{categoria}}{% if view.request.GET.marca != None %}&marca={{view.request.GET.marca}}{% endif %}&page={{ page_obj.next_page_number }}" class="next-arrow"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
						{% endif %}
					</div>
					{% endif %}
					
					
					
				</div>
                <!-- End Filter Bar -->
                
                
                
                    
                
                    
				<!-- Start Best Seller -->
				<section class="lattest-product-area pb-40 category-list">
					<div class="row">
                            {% for item in object_list %}
						<!-- single product -->
						<div class="col-lg-4 col-md-6">
							<div class="single-product">
								<img class="img-fluid" src="{{item.prod_miniatura.url}}" alt="">
								<div class="product-details">
									<h6>{{item.prod_nombre}}</h6>
									<div class="price">
										<h6>${{item.prod_con_descuento|intcomma}}</h6>
										<h6 class="l-through">${{item.prod_precio|intcomma}}</h6>
									</div>
									<div class="prd-bottom">

										<!-- <a href="" class="social-info">
											<span class="ti-bag"></span>
											<p class="hover-text">añadir</p>
										</a> -->
										<!-- <a href="" class="social-info">
											<span class="lnr lnr-heart"></span>
											<p class="hover-text">deseos</p>
										</a> -->
										<!-- <a href="" class="social-info">
											<span class="lnr lnr-sync"></span>
											<p class="hover-text">comparar</p>
										</a> -->
										<a href="{% url 'index:detalle' item.prod %}" class="social-info">
											<span class="lnr lnr-move"></span>
											<p class="hover-text">ver mas</p>
										</a>
									</div>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</section>
				<!-- End Best Seller -->
				<!-- Start Filter Bar -->
				<div class="filter-bar d-flex flex-wrap align-items-center">
						{% if is_paginated %}
						<div class="pagination">
							{% if page_obj.has_previous %}
							<a href="?cat={{categoria}}{% if view.request.GET.marca != None %}&marca={{view.request.GET.marca}}{% endif %}&page={{ page_obj.previous_page_number }}" class="prev-arrow"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
							{% endif %}
							{% for page in page_obj.paginator.page_range %}
									<a href="?cat={{categoria}}{% if view.request.GET.marca != None %}&marca={{view.request.GET.marca}}{% endif %}&page={{ page }}" class="{% if page_obj.number == page %}active{% endif %}">{{ page }}</a>
							{% endfor %}
							{% if page_obj.has_next %}
							<a href="?cat={{categoria}}{% if view.request.GET.marca != None %}&marca={{view.request.GET.marca}}{% endif %}&page={{ page_obj.next_page_number }}" class="next-arrow"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
							{% endif %}
						</div>
						{% endif %}
				</div>
				<!-- End Filter Bar -->
			</div>
		</div>
	</div>


	
{% endblock contenido %}

templates/index/salir.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ela Admin - HTML5 Admin Template</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link type="image/x-icon" href="{% static 'imagenes/icons8-wolf-filled-24.png' %}" rel="icon" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'administracion/assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'administracion/assets/css/style.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
</head>
<body class="bg-secondary">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="{% static 'imagenes/path12.png' %}" alt="">
                    </a>
                </div>
                <div class="login-form">
                    <h5 class="text-center">GRACIAS</h5>
                    <br>
                    <p>
                    Fue un placer, y estamos muy contentos de que hayamos tenido la oportunidad de haber visitarnos. Sé que este es un momento emocionante y potencialmente intenso para usted, así que déjeme decirle que está en buenas manos. Nos aseguraremos que nuestro equipo le brinde una variedad de opciones. Gracias por su visita, y espero verle pronto.
                </p>
                <a href="{% url 'inicio' %}" class="btn btn-link">Iniciar sesion nuevamente</a>
                    </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="assets/js/main.js"></script>

</body>
</html>